#!/bin/sh

cargo +nightly build --release
/opt/devkitpro/devkitPPC/bin/powerpc-eabi-strip -g target/powerpc-unknown-eabi/release/wut-rust-demo
elf2rpl target/powerpc-unknown-eabi/release/wut-rust-demo wut-rust-demo.rpx
