[package]
name = "wut-rust-demo"
version = "0.1.0"
authors = ["wut-rust-demo"]
edition = "2018"

[[bin]]
name = "wut-rust-demo"

[dependencies]
cafeos = { path = "cafeos" }
cafeos-sys = { path = "cafeos-sys" }
