[package]
name = "rust-wii"
version = "0.1.0"
authors = ["rust-wii"]
edition = "2018"

[[bin]]
name = "rust-wii"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
libc = "0.2"

[dependencies.arrayvec]
version = "0.5.2"
default-features = false
