[package]
name = "cafeos"
version = "0.1.0"
authors = ["James Benton <james.benton2@gmail.com>"]
edition = "2018"

[dependencies]
cty = "0.2.1"
cafeos-sys = { path = "../cafeos-sys" }

[dependencies.arrayvec]
version = "0.5.2"
default-features = false

